### PR TITLE
Custom CSS

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Re-addresses #62 , even though theming isn't the nicest with the current Google Chat version, it's still possible.

Also migrates the lockfile to v3 for speed and compatibility

### CODE REVIEW

**Comment by squalou** [comment]
Amazing !
thanks, will merge it asap

**Comment by ThatOneCalculator** [comment]
Just woke up, I'll do that a bit later today 👍

**Comment by ThatOneCalculator** [comment]
@squalou should be good now

**Comment by squalou** [comment]
looks much better ! thanks

Merging it,
release asap

**Comment by squalou** [comment]
OMG
I should have tested more, maybe due to my connexion (holiday \o/) or electron : clicking on people or rooms does not display them :-)

I don't know if you can reproduce,
will try to debug it, maybe it's local to my setup

**Comment by ThatOneCalculator** [comment]
That's really strange... I can't reproduce that issue at all. At least not with the Electron version that was used while writing this PR (I saw you upgraded it after)

**Comment by squalou** [comment]
release done :)

**Pull request merged**
